wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 25
max_size:
  desc: null
  value: 1166
subset:
  desc: null
  value: true
subset_size:
  desc: null
  value: 0.1
batchsize:
  desc: null
  value: 2048
dataset:
  desc: null
  value: gold_stand
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699022502.976258
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
