wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 100
batchsize:
  desc: null
  value: 16
dataset:
  desc: null
  value: Huang
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698075730.616284
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
